name: 🪲 Report a bug
description: Create a bug report to help improve MultiProtocol Firmware
title: "[BUG] (bug summary)"
labels: 'New protocol'
body:
  - type: markdown
    attributes:
      value: >
        Before creating new Issue, please search through: 

        - [Existing issues](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues)

        - [Discussions page](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/discussions)

        - [Official forum](https://www.rcgroups.com/forums/showthread.php?2165676-DIY-Multiprotocol-TX-Module/page10000)

  - type: dropdown
    attributes:
      label: Have you tested with the latest release version?
      description: >-
        Always try the latest code to make sure the issue you are reporting is not already fixed. To download
        the latest code just [click this link](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases).
      options:
        - Yes, and the problem still exists.
        - No, but I will test it now!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Your Setup

  - type: input
    attributes:
      label: Version of MultiProtocol firmware
      placeholder: something like `v1.3.3.20`
    validations:
      required: true

  - type: input
    attributes:
      label: Protocol (optional)
      description: "One of [existing protocols](https://www.multi-module.org/using-the-module/protocol-details)"
      placeholder: 'Asan / Bayang / ... '

  - type: input
    attributes:
      label: Remote / Controller / Transmitter model
      placeholder: 'Jumper T-pro, Radiomaster TX16 MK2, external name...'

  - type: input
    attributes:
      label: Receiver / Device model / type
      placeholder: 'EACHINE E010 Drone'

  - type: markdown
    attributes:
      value: |
        # Bug Details

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
      placeholder: |
        Marlin doesn't work.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen?
      placeholder: I expected it to move left.

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: It moved right instead of left.

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...
