name: 🪲 Report a bug
description: Create a bug report to help improve MultiProtocol Firmware
title: "[BUG] (bug summary)"
labels: 'New protocol'
body:
  - type: markdown
    attributes:
      value: >
        Do you want to ask a question? Are you looking for support? Please use one of the [support links](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug in Marlin Firmware!**

        ## Before Reporting a Bug

        - Read and understand Marlin's [Code of Conduct](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/code_of_conduct.md). You are expected to comply with it, including treating everyone with respect.

        - Test with the [`bugfix-2.1.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to see whether the issue still exists.

        ## Instructions

        Please follow the instructions below. Failure to do so may result in your issue being closed. See [Contributing to Marlin](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md) for additional guidelines.

        1. Provide a good title starting with [BUG].
        2. Fill out all sections of this bug report form.
        3. Always attach configuration files so we can build and test your setup.

  - type: dropdown
    attributes:
      label: Have you tested with the latest release version?
      description: >-
        Always try the latest code to make sure the issue you are reporting is not already fixed. To download
        the latest code just [click this link](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases).
      options:
        - Yes, and the problem still exists.
        - No, but I will test it now!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Bug Details

  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        Describe the bug in this section. Tell us what you were trying to do and what
        happened that you did not expect. Provide a clear and concise description of the
        problem and include as many details as possible.

        When pasting formatted text don't forget to put ` ``` ` (on its own line) before and after to make it readable.
      placeholder: |
        Marlin doesn't work.
    validations:
      required: true

  - type: input
    attributes:
      label: Bug Timeline
      description: Is this a new bug or an old issue? When did it first start?

  - type: textarea
    attributes:
      label: Expected behavior
      description: >-
        What did you expect to happen?
      placeholder: I expected it to move left.

  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened instead?
      placeholder: It moved right instead of left.

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >-
        Please describe the steps needed to reproduce the issue.
      placeholder: |
        1. [First Step] ...
        2. [Second Step] ...
        3. [and so on] ...

  - type: markdown
    attributes:
      value: |
        # Your Setup

  - type: input
    attributes:
      label: Version of MultiProtocol firmware
      description: "See the About Menu on the LCD or the output of `M115`. NOTE: For older releases we only patch critical bugs."
    validations:
      required: true

  - type: input
    attributes:
      label: Remote / Controller / Transmitter model
      description: 'Jumper T-pro, Radiomaster TX16 MK2, etc..'

  - type: input
    attributes:
      label: Receiver / Device model
      description: 'EACHINE E010'
