name: ✨ New device support request
description: Request support for new device
title: "(Please put here manufacturer, model & device type - for example EACHINE E010 Drone)"
labels: 'New protocol'
body:
  - type: markdown
    attributes:
      value: >
        Before creating new request, please search through: 

        - [Discussions page](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/discussions)

        - [Official forum](https://www.rcgroups.com/forums/showthread.php?2165676-DIY-Multiprotocol-TX-Module/page10000)

        - Also same manufacturer can have devices with different protocol (like Eachine drones). 
          It's worth trying existing devices from same manufacturer just in case.

  - type: textarea
    attributes:
      label: Provide any other useful information
      description: >
        - Can you search [fccid site](https://fccid.io/company.php). Use company name. Usually it would find have few entries for same manufacturer. 
        Go through the devices & try to find your specific device. It will help you find disassembled device & some useful technical information.

        - **unless fcc did not produce any results & under your own responsibility:** Can you disassemble device & take a look inside receiver & transmitter ? It would be useful to know what chip is used inside.

        - Can you take a photo of device / controller, paste them here, and do [google image search](https://images.google.com) for similar devices ?